### PR TITLE
Minor: Update stylelint to 7.8.0

### PR DESCRIPTION
**Pull request by pichfl**
The current release of stylelint introduces a few useful additions and rules. 

If this request is ready to merge and approved I'll file another one over at ember-cli-stylelint to update its dependencies as well.

Thank you so much for creating this plugin.

### CODE REVIEW

**Comment by amk221** [comment]
Thanks @pichfl I'm waiting for this to go in ☺️

**Comment by billybonks** [comment]
why did you change it to version 0.12 ?

**Comment by pichfl** [comment]
Oh shoot, I think my release script went over the top. Will do.

**Comment by billybonks** [comment]
no problem. i made the change and added it to ember-cli-stylelint everything should be working now thanks for your pr 👍

**Pull request merged**
