### PR TITLE
Bump stylelint

### PR DESCRIPTION
**Pull request by rwwagner90**

### CODE REVIEW

**Comment by rwwagner90** [comment]
@billybonks would you mind taking a look at this?

**Comment by billybonks** [comment]
apologies for the delay didn't know this PR was opened. will look into this today. thanks :)

**Comment by rwwagner90** [comment]
@billybonks no worries! It's just a simple version bump. It avoids some peerDep issues I have been having.

**Comment by rwwagner90** [comment]
Can we please get this update in? 😄

**Comment by billybonks** [comment]
sorry for the delay again 👍, been crazy busy. I never merged because it broke `ignore paths` test
similar issue too, https://github.com/stylelint/stylelint/issues/2833. Since version 8 it seems to not care about the ignore file if you pass code directly. a short term fix would be to rebuild the ignore logic into this addon, but ideally, the ignore logic should lie with stylelint. I'll join in the conversation and see what they have to say.

**Comment by billybonks** [comment]
https://github.com/billybonks/broccoli-stylelint/pull/34

**Comment by billybonks** [comment]
@rwwagner90 I have created a pr that fixes the bug in stylelint hopefully I can get it merged by the end of the week, then we can update this library with no regressions.

https://github.com/stylelint/stylelint/pull/2897

**Comment by rwwagner90** [comment]
@billybonks I'd love to get this bumped. Would love to get rid of these:

```
warning "stylelint-config-ship-shape@0.1.3" has unmet peer dependency "stylelint@^8.0.0".
warning "stylelint-config-standard@17.0.0" has unmet peer dependency "stylelint@^8.0.0".
warning "stylelint-scss@2.1.0" has unmet peer dependency "stylelint@^8.0.0".
warning "stylelint-config-recommended@1.0.0" has unmet peer dependency "stylelint@^8.0.0".
```

**Comment by billybonks** [comment]
This has been resolved, sorry for the delay, there was a bug in stylelint, which I have temporarily fixed here. please use v1.

**Pull request closed without merging**
